# Dockerfile for creating a Docker image that contains the .NET Core app's FDD
# It requires the FDD to be already built.

FROM microsoft/dotnet:1.1-runtime-nanoserver

LABEL maintainer "Philipp Gille"

WORKDIR /dotnetapp
COPY artifacts/hello-netcoreapp_netcoreapp1.1 .

ENTRYPOINT ["dotnet", "hello-netcoreapp.dll"]