# Dockerfile for creating a Docker image that contains the .NET Core app's FDD
# It requires the FDD to be already built.

FROM microsoft/dotnet:2.0-runtime

LABEL maintainer "Philipp Gille"

WORKDIR /dotnetapp
COPY artifacts/hello-netcoreapp_v*_netcoreapp2.0 ./

ENTRYPOINT ["dotnet", "hello-netcoreapp.dll"]